name: wonder_minon
description: Pazzle Game for flutter and html5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  umiuni2d_sprite:
    git:
      url: https://github.com/kyorohiro/umiuni2d_sprite.git
      ref: v0.0.4
  umiuni2d_sprite_flutter:
    git:
      url: https://github.com/kyorohiro/umiuni2d_sprite_flutter.git
      ref: v0.0.4
  umiuni2d_sprite_html5:
    git:
      url: https://github.com/kyorohiro/umiuni2d_sprite_html5.git
      ref: v0.0.4
flutter:
  uses-material-design: true
  assets:
   - web/assets/bg_clear01.png
   - web/assets/bg_clear02.png
   - web/assets/bg_clear03.png
   - web/assets/bg_clear04.png
   - web/assets/bg_clear05.png
   - web/assets/bg_clear06.png
   - web/assets/se_start.png
   - web/assets/se_start.json
   - web/assets/font_a.json
   - web/assets/font_a.png
   - web/assets/se_play.json
   - web/assets/se_play.png
   - web/assets/se_setting.json
   - web/assets/se_setting.png
   - web/assets/greendog.mp3
   - web/assets/se_maoudamashii_se_syber04.mp3
   - web/assets/se_maoudamashii_se_syber08.mp3
   - web/assets/se_maoudamashii_se_syber09.mp3
